<?php
declare(strict_types=1);
session_start();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
require_once __DIR__ . '/config.php';

function J(array $data, int $status = 200): never { http_response_code($status); echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); exit; }
function D(): array { $raw=file_get_contents('php://input'); if($raw!==false&&trim($raw)!==''){ $json=json_decode($raw,true); if(is_array($json)) return $json; } return $_POST; }
function currentUser(): array { if(empty($_SESSION['user'])) J(['ok'=>false,'error'=>'Login required'],401); return $_SESSION['user']; }
function adminUser(): array { $user=currentUser(); if(strtoupper((string)($user['role']??''))!=='ADMIN') J(['ok'=>false,'error'=>'Administrator access required'],403); return $user; }
function validULD(string $uld): bool { return in_array(strtoupper($uld),['AKE','PAJ','PMC','PAG'],true); }
function col(PDO $pdo,string $table,string $column): bool { $q=$pdo->prepare('SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?'); $q->execute([$table,$column]); return (int)$q->fetchColumn()>0; }
function setting(PDO $pdo,string $key,string $default=''): string { $q=$pdo->prepare('SELECT setting_value FROM madapt_settings WHERE setting_key=? LIMIT 1'); $q->execute([$key]); $v=$q->fetchColumn(); return $v===false?$default:(string)$v; }
function saveSetting(PDO $pdo,string $key,string $value): void { $q=$pdo->prepare('INSERT INTO madapt_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)'); $q->execute([$key,$value]); }
function ensureRecipientsTable(PDO $pdo): void { $pdo->exec("CREATE TABLE IF NOT EXISTS madapt_alert_recipients (id INT UNSIGNED NOT NULL AUTO_INCREMENT,email VARCHAR(190) NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_alert_email(email)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); }
function saveImageUpload(string $field,string $folder,string $prefix): string { if(empty($_FILES[$field])||!is_array($_FILES[$field])) throw new RuntimeException('No image file received'); $f=$_FILES[$field]; if((int)($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK) throw new RuntimeException('Image upload failed'); if((int)$f['size']>5*1024*1024) throw new RuntimeException('Image must be 5 MB or smaller'); $tmp=(string)$f['tmp_name']; if(!is_uploaded_file($tmp)) throw new RuntimeException('Invalid upload'); $info=@getimagesize($tmp); if($info===false) throw new RuntimeException('Only valid image files are allowed'); $mime=(string)($info['mime']??''); $exts=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp']; if(!isset($exts[$mime])) throw new RuntimeException('Allowed formats: JPG, PNG or WEBP'); $root=__DIR__.'/uploads/'.$folder; if(!is_dir($root)&&!mkdir($root,0755,true)&&!is_dir($root)) throw new RuntimeException('Could not create upload directory'); $name=$prefix.'_'.bin2hex(random_bytes(8)).'.'.$exts[$mime]; $target=$root.'/'.$name; if(!move_uploaded_file($tmp,$target)) throw new RuntimeException('Could not save uploaded image'); return 'uploads/'.$folder.'/'.$name; }

try {
$pdo=db(); $action=trim((string)($_GET['action']??''));
if($action==='login'){ $d=D();$username=trim((string)($d['username']??''));$password=(string)($d['password']??''); if($username===''||$password==='')J(['ok'=>false,'error'=>'Username and password required'],400);$q=$pdo->prepare('SELECT id,username,password_hash,full_name,email,profile_photo,role,active,created_at FROM users WHERE username=? LIMIT 1');$q->execute([$username]);$user=$q->fetch(PDO::FETCH_ASSOC);if(!$user||!(int)$user['active']||!password_verify($password,$user['password_hash']))J(['ok'=>false,'error'=>'Invalid username or password'],401);unset($user['password_hash']);session_regenerate_id(true);$_SESSION['user']=$user;J(['ok'=>true,'user'=>$user]); }
if($action==='logout'){$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),' ',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();J(['ok'=>true]);}
if($action==='me')J(['ok'=>true,'user'=>currentUser()]);
if($action==='register'){ $d=D();$username=trim((string)($d['username']??''));$name=trim((string)($d['full_name']??''));$email=trim((string)($d['email']??''));$password=(string)($d['password']??'');if($username===''||$name===''||$password==='')J(['ok'=>false,'error'=>'Username, full name and password are required'],400);if(strlen($password)<8)J(['ok'=>false,'error'=>'Password must contain at least 8 characters'],400);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))J(['ok'=>false,'error'=>'Invalid email address'],400);$q=$pdo->prepare('SELECT id FROM users WHERE username=? LIMIT 1');$q->execute([$username]);if($q->fetch())J(['ok'=>false,'error'=>'Username already exists'],409);$q=$pdo->prepare('INSERT INTO users(username,password_hash,full_name,email,role,active) VALUES(?,?,?,?,"OPERATOR",0)');$q->execute([$username,password_hash($password,PASSWORD_DEFAULT),$name,$email?:null]);J(['ok'=>true,'message'=>'Account created and waiting for administrator approval.']); }
$me=currentUser();
if($action==='stock'){ $stock=$pdo->query("SELECT uld_type,opening_stock,current_stock,minimum_level,updated_at FROM uld_stock ORDER BY FIELD(uld_type,'AKE','PAJ','PMC','PAG')")->fetchAll(PDO::FETCH_ASSOC);$sql=col($pdo,'uld_movements','flight_number')?"SELECT id,movement_type,uld_type,quantity,reference,remarks,flight_number,user_name,created_at FROM uld_movements ORDER BY id DESC LIMIT 500":"SELECT id,movement_type,uld_type,quantity,reference,remarks,NULL AS flight_number,user_name,created_at FROM uld_movements ORDER BY id DESC LIMIT 500";$movements=$pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);$low=array_values(array_filter($stock,static fn($row)=>(int)$row['current_stock']<=(int)$row['minimum_level']));$flights=[];try{$flights=$pdo->query("SELECT id,flight_number,active FROM madapt_flights WHERE active=1 ORDER BY flight_number ASC")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}J(['ok'=>true,'stock'=>$stock,'low_stock'=>$low,'movements'=>$movements,'flights'=>$flights]); }
if($action==='history'){ $sql=col($pdo,'uld_movements','flight_number')?"SELECT id,movement_type,uld_type,quantity,reference,remarks,flight_number,user_name,created_at FROM uld_movements ORDER BY id DESC LIMIT 1000":"SELECT id,movement_type,uld_type,quantity,reference,remarks,NULL AS flight_number,user_name,created_at FROM uld_movements ORDER BY id DESC LIMIT 1000";$history=$pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);J(['ok'=>true,'history'=>$history,'movements'=>$history]); }
if($action==='movement'){ $d=D();$uld=strtoupper(trim((string)($d['uld_type']??'')));$type=strtoupper(trim((string)($d['movement_type']??$d['type']??'')));$qty=(int)($d['quantity']??$d['qty']??0);$flight=strtoupper(trim((string)($d['flight_number']??$d['flight']??'')));$ref=trim((string)($d['reference']??''));$remarks=trim((string)($d['remarks']??''));if(!validULD($uld))J(['ok'=>false,'error'=>'Invalid ULD type'],400);if(!in_array($type,['IN','OUT'],true))J(['ok'=>false,'error'=>'Invalid movement type'],400);if($qty<1)J(['ok'=>false,'error'=>'Quantity must be at least 1'],400);if($flight!==''&&!preg_match('/^[A-Z]{2,3}[0-9]{1,5}$/',$flight))J(['ok'=>false,'error'=>'Invalid flight number'],400);$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT current_stock FROM uld_stock WHERE uld_type=? FOR UPDATE');$q->execute([$uld]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('ULD type not found');$cur=(int)$row['current_stock'];if($type==='OUT'&&$qty>$cur)throw new RuntimeException("Insufficient $uld stock. Current stock: $cur");$new=$type==='IN'?$cur+$qty:$cur-$qty;$q=$pdo->prepare('UPDATE uld_stock SET current_stock=?,updated_at=CURRENT_TIMESTAMP WHERE uld_type=?');$q->execute([$new,$uld]);if(col($pdo,'uld_movements','flight_number')){$q=$pdo->prepare('INSERT INTO uld_movements(movement_type,uld_type,quantity,reference,remarks,flight_number,user_name) VALUES(?,?,?,?,?,?,?)');$q->execute([$type,$uld,$qty,$ref,$remarks,$flight?:null,$me['full_name']??$me['username']]);}else{$stored=$remarks;if($flight)$stored=$stored!==''?$stored.' | Flight: '.$flight:'Flight: '.$flight;$q=$pdo->prepare('INSERT INTO uld_movements(movement_type,uld_type,quantity,reference,remarks,user_name) VALUES(?,?,?,?,?,?)');$q->execute([$type,$uld,$qty,$ref,$stored,$me['full_name']??$me['username']]);}$pdo->commit();J(['ok'=>true,'new_stock'=>$new]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }
if($action==='users'){adminUser();$users=$pdo->query('SELECT id,username,full_name,email,role,active,profile_photo,created_at FROM users ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);J(['ok'=>true,'users'=>$users]);}
if($action==='approve'){adminUser();$d=D();$q=$pdo->prepare('UPDATE users SET active=? WHERE id=?');$q->execute([strtolower((string)($d['status']??'approved'))==='approved'?1:0,(int)($d['id']??0)]);J(['ok'=>true]);}
if($action==='set_role'){adminUser();$d=D();$role=strtoupper(trim((string)($d['role']??'')));if(!in_array($role,['ADMIN','SUPERVISOR','OPERATOR'],true))J(['ok'=>false,'error'=>'Invalid role'],400);$q=$pdo->prepare('UPDATE users SET role=? WHERE id=?');$q->execute([$role,(int)($d['id']??0)]);J(['ok'=>true]);}
if($action==='delete_user'){adminUser();$id=(int)(D()['id']??0);if($id===(int)$me['id'])J(['ok'=>false,'error'=>'You cannot delete your own account'],400);$q=$pdo->prepare('DELETE FROM users WHERE id=?');$q->execute([$id]);J(['ok'=>true]);}
if($action==='change_password'){ $d=D();$old=(string)($d['old_password']??'');$new=(string)($d['new_password']??'');$q=$pdo->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$me['id']]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row||!password_verify($old,$row['password_hash']))J(['ok'=>false,'error'=>'Current password is incorrect'],400);if(strlen($new)<8)J(['ok'=>false,'error'=>'New password must contain at least 8 characters'],400);$q=$pdo->prepare('UPDATE users SET password_hash=? WHERE id=?');$q->execute([password_hash($new,PASSWORD_DEFAULT),$me['id']]);J(['ok'=>true]);}
if($action==='set_minimum'){adminUser();$d=D();$uld=strtoupper((string)($d['uld_type']??''));$minimum=(int)($d['minimum_level']??0);if(!validULD($uld)||$minimum<0)J(['ok'=>false,'error'=>'Invalid ULD or minimum level'],400);$q=$pdo->prepare('UPDATE uld_stock SET minimum_level=? WHERE uld_type=?');$q->execute([$minimum,$uld]);J(['ok'=>true]);}

if($action==='settings_get'){ adminUser();$settings=[];$q=$pdo->query('SELECT setting_key,setting_value FROM madapt_settings');foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r)$settings[$r['setting_key']]=$r['setting_value'];$flights=[];$recipients=[];try{$flights=$pdo->query('SELECT id,flight_number,active,created_at FROM madapt_flights ORDER BY flight_number')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}try{ensureRecipientsTable($pdo);$recipients=$pdo->query('SELECT id,email,active,created_at FROM madapt_alert_recipients ORDER BY email')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}J(['ok'=>true,'settings'=>$settings,'flights'=>$flights,'recipients'=>$recipients]); }
if($action==='settings_save'){ adminUser();$d=D();foreach(['company_name','primary','accent','sidebar','logo_path','aircraft_path','low_stock_alerts','low_stock_email_subject','low_stock_email_message'] as $k)if(array_key_exists($k,$d))saveSetting($pdo,$k,trim((string)$d[$k]));J(['ok'=>true]); }
if($action==='settings_email_save'){ adminUser();$d=D();saveSetting($pdo,'low_stock_alerts',!empty($d['enabled'])?'1':'0');saveSetting($pdo,'low_stock_email_subject',trim((string)($d['subject']??'')));saveSetting($pdo,'low_stock_email_message',(string)($d['message']??''));J(['ok'=>true]); }
if($action==='email_add'||$action==='alert_email_add'){ adminUser();ensureRecipientsTable($pdo);$d=D();$email=trim((string)($d['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))J(['ok'=>false,'error'=>'Invalid email address'],400);try{$q=$pdo->prepare('INSERT INTO madapt_alert_recipients(email,active) VALUES(?,1) ON DUPLICATE KEY UPDATE active=1');$q->execute([$email]);}catch(Throwable $e){J(['ok'=>false,'error'=>'Could not add recipient: '.$e->getMessage()],500);}J(['ok'=>true]); }
if($action==='email_toggle'||$action==='alert_email_toggle'){ adminUser();ensureRecipientsTable($pdo);$id=(int)(D()['id']??0);$q=$pdo->prepare('UPDATE madapt_alert_recipients SET active=IF(active=1,0,1) WHERE id=?');$q->execute([$id]);J(['ok'=>true]); }
if($action==='email_delete'||$action==='alert_email_delete'){ adminUser();ensureRecipientsTable($pdo);$id=(int)(D()['id']??0);$q=$pdo->prepare('DELETE FROM madapt_alert_recipients WHERE id=?');$q->execute([$id]);J(['ok'=>true]); }
if($action==='flight_add'){ adminUser();$d=D();$flight=strtoupper(trim((string)($d['flight_number']??'')));if(!preg_match('/^[A-Z]{2,3}[0-9]{1,5}$/',$flight))J(['ok'=>false,'error'=>'Invalid flight number'],400);$q=$pdo->prepare('INSERT INTO madapt_flights(flight_number,active) VALUES(?,1)');$q->execute([$flight]);J(['ok'=>true,'id'=>(int)$pdo->lastInsertId()]); }
if($action==='flight_toggle'){ adminUser();$id=(int)(D()['id']??0);$q=$pdo->prepare('UPDATE madapt_flights SET active=IF(active=1,0,1) WHERE id=?');$q->execute([$id]);J(['ok'=>true]); }
if($action==='flight_delete'){ adminUser();$id=(int)(D()['id']??0);$q=$pdo->prepare('DELETE FROM madapt_flights WHERE id=?');$q->execute([$id]);J(['ok'=>true]); }

if($action==='asset_upload'){ adminUser();$kind=trim((string)($_POST['kind']??''));$map=['logo'=>['logo','branding','logo'],'aircraft'=>['aircraft','branding','aircraft']];if(!isset($map[$kind]))J(['ok'=>false,'error'=>'Invalid asset type'],400);try{$path=saveImageUpload($map[$kind][0],$map[$kind][1],$map[$kind][2]);saveSetting($pdo,$kind.'_path',$path);J(['ok'=>true,'path'=>$path]);}catch(Throwable $e){J(['ok'=>false,'error'=>$e->getMessage()],400);} }
if($action==='profile_upload'){ $user=currentUser();try{$path=saveImageUpload('profile_photo','profiles','profile_'.$user['id']);$q=$pdo->prepare('UPDATE users SET profile_photo=? WHERE id=?');$q->execute([$path,$user['id']]);$_SESSION['user']['profile_photo']=$path;J(['ok'=>true,'profile_photo'=>$path]);}catch(Throwable $e){J(['ok'=>false,'error'=>$e->getMessage()],400);} }

if($action==='portals'){try{$portals=$pdo->query("SELECT id,name,url,description,logo_path,active,sort_order FROM madapt_portals WHERE active=1 ORDER BY sort_order,name")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){J(['ok'=>false,'error'=>'Portals table is not installed. Import madapt_portals.sql first.'],500);}J(['ok'=>true,'portals'=>$portals]);}
if($action==='portal_add'){adminUser();$d=D();$name=trim((string)($d['name']??''));$url=trim((string)($d['url']??''));if($name===''||$url==='')J(['ok'=>false,'error'=>'Portal name and URL are required'],400);$q=$pdo->prepare('INSERT INTO madapt_portals(name,url,description,logo_path,active,sort_order) VALUES(?,?,?,?,1,0)');$q->execute([$name,$url,trim((string)($d['description']??'')),trim((string)($d['logo_path']??''))]);J(['ok'=>true,'id'=>(int)$pdo->lastInsertId()]);}
if($action==='portal_update'){adminUser();$d=D();$q=$pdo->prepare('UPDATE madapt_portals SET name=?,url=?,description=?,logo_path=? WHERE id=?');$q->execute([trim((string)($d['name']??'')),trim((string)($d['url']??'')),trim((string)($d['description']??'')),trim((string)($d['logo_path']??'')),(int)($d['id']??0)]);J(['ok'=>true]);}
if($action==='portal_delete'){adminUser();$q=$pdo->prepare('DELETE FROM madapt_portals WHERE id=?');$q->execute([(int)(D()['id']??0)]);J(['ok'=>true]);}
if($action==='portal_logo_upload'){adminUser();$id=(int)($_POST['portal_id']??0);if($id<1)J(['ok'=>false,'error'=>'Invalid portal'],400);$q=$pdo->prepare('SELECT id FROM madapt_portals WHERE id=? LIMIT 1');$q->execute([$id]);if(!$q->fetch())J(['ok'=>false,'error'=>'Portal not found'],404);try{$path=saveImageUpload('portal_logo','portals','portal_'.$id);$q=$pdo->prepare('UPDATE madapt_portals SET logo_path=? WHERE id=?');$q->execute([$path,$id]);J(['ok'=>true,'logo_path'=>$path]);}catch(Throwable $e){J(['ok'=>false,'error'=>$e->getMessage()],400);} }
J(['ok'=>false,'error'=>'Unknown action','action'=>$action],400);
}catch(Throwable $e){error_log('MADAPT API ERROR: '.$e->getMessage());J(['ok'=>false,'error'=>'Internal server error'],500);}
