<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
require_once __DIR__ . '/config.php';
if (empty($_SESSION['user'])) { header('Location: login.php'); exit; }
$user = $_SESSION['user'];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OPERACIONES — MADAPT ULDs</title><link rel="stylesheet" href="assets/app.css">
<style>
.ops-page{max-width:1500px;margin:auto;padding:24px}.ops-top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.ops-top h1{margin:0}.ops-controls{display:flex;gap:8px;flex-wrap:wrap}.ops-btn{border:0;border-radius:8px;padding:10px 14px;font-weight:700;cursor:pointer;background:#087a46;color:#fff}.ops-btn.secondary{background:#e7efeb;color:#18322a}.ops-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:20px 0}.ops-card{background:#fff;border:1px solid #dce7e3;border-radius:12px;padding:16px}.ops-card h3{margin:0 0 8px}.ops-value{font-size:27px;font-weight:800}.ops-note{font-size:13px;color:#60756d}.ops-group{margin:18px 0}.ops-group h2{font-size:18px;margin:0 0 8px}.ops-table{width:100%;border-collapse:collapse;background:#fff}.ops-table th,.ops-table td{padding:9px;border-bottom:1px solid #e5ece9;text-align:left}.ops-table th{background:#f0f6f3}.ops-status{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800}.pending{background:#edf1ef}.started{background:#fff0c8}.completed{background:#dff4e8}.ops-action{border:0;border-radius:6px;padding:6px 9px;font-weight:700;cursor:pointer}.ops-start{background:#e8f5ee;color:#087a46}.ops-complete{background:#087a46;color:#fff}.ops-form{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.ops-form label{display:flex;flex-direction:column;gap:4px;font-size:12px;font-weight:700}.ops-form input{padding:9px;border:1px solid #cbdad4;border-radius:7px}@media(max-width:900px){.ops-cards{grid-template-columns:repeat(2,minmax(0,1fr))}.ops-page{padding:14px}.ops-table{font-size:12px}}@media(max-width:600px){.ops-cards{grid-template-columns:1fr}.ops-table th:nth-child(4),.ops-table td:nth-child(4),.ops-table th:nth-child(5),.ops-table td:nth-child(5){display:none}}
</style></head><body>
<div class="ops-page"><div class="ops-top"><div><h1>OPERACIONES</h1><div class="ops-note">B787-900 Ground Turnaround · 70 minutos</div></div><div class="ops-controls"><button class="ops-btn secondary" onclick="location.href='index.php'">← MADAPT ULDs</button><button class="ops-btn secondary" onclick="loadOps()">↻ Actualizar</button></div></div>
<div class="ops-cards"><div class="ops-card"><h3>Block-In</h3><div class="ops-value" id="blockIn">—</div><div class="ops-note">Inicio del turnaround</div></div><div class="ops-card"><h3>Total</h3><div class="ops-value" id="total">—</div><div class="ops-note">Operaciones planificadas</div></div><div class="ops-card"><h3>En curso</h3><div class="ops-value" id="started">—</div><div class="ops-note">Started</div></div><div class="ops-card"><h3>Completadas</h3><div class="ops-value" id="completed">—</div><div class="ops-note">Completed</div></div></div>
<div class="ops-card"><h3>Control de turnaround</h3><div class="ops-form"><label>Hora Block-In<input id="blockInput" type="datetime-local"></label><button class="ops-btn" onclick="setBlockIn()">Guardar Block-In</button><button class="ops-btn secondary" onclick="resetOps()">Reset operaciones</button></div></div>
<div id="operationGroups"></div></div>
<script>
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function api(action,body={}){return fetch('operations.php?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(async r=>{const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j})}
function fmt(v){if(!v)return'—';const d=new Date(String(v).replace(' ','T'));return isNaN(d)?v:d.toLocaleString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
async function loadOps(){try{const j=await api('data');document.getElementById('blockIn').textContent=fmt(j.blockIn);document.getElementById('total').textContent=j.summary.total;document.getElementById('started').textContent=j.summary.started;document.getElementById('completed').textContent=j.summary.completed;const groups={};(j.operations||[]).forEach(x=>(groups[x.op_group]??=[]).push(x));document.getElementById('operationGroups').innerHTML=Object.entries(groups).map(([g,rows])=>`<div class="ops-group"><h2>${esc(g)}</h2><div style="overflow:auto"><table class="ops-table"><thead><tr><th>No.</th><th>Operación</th><th>Plan</th><th>Asignado</th><th>Operador</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows.map(x=>{const s=(x.status||'Pending').toLowerCase();const action=x.status==='Started'?`<button class="ops-action ops-complete" onclick="changeOp(${x.id},'Completed')">COMPLETE</button>`:x.status==='Completed'?'✓':`<button class="ops-action ops-start" onclick="changeOp(${x.id},'Started')">START</button>`;return`<tr><td>${x.operation_no}</td><td><b>${esc(x.operation_name)}</b></td><td>${esc(x.planned_start)}${x.planned_end?' → '+esc(x.planned_end):''}</td><td>${esc(x.allocated)}</td><td>${esc(x.operator_name)}</td><td><span class="ops-status ${s}">${esc(x.status||'Pending')}</span></td><td>${action}</td></tr>`}).join('')}</tbody></table></div></div>`).join('')}catch(e){document.getElementById('operationGroups').innerHTML='<div class="ops-card">'+esc(e.message)+'</div>'}}
async function changeOp(id,action){try{await api('update',{id,operation_action:action});await loadOps()}catch(e){alert(e.message)}}
async function setBlockIn(){const v=document.getElementById('blockInput').value;if(!v)return alert('Select Block-In time');try{await api('block_in',{iso:new Date(v).toISOString()});await loadOps()}catch(e){alert(e.message)}}
async function resetOps(){if(!confirm('Reset all operation statuses?'))return;try{await api('reset');await loadOps()}catch(e){alert(e.message)}}
loadOps();setInterval(loadOps,15000);
</script></body></html>
